# Generated by Django 3.1.6 on 2022-06-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MstPokemon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('poke_name', models.CharField(max_length=256, verbose_name='ポケモン名')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='レベル')),
                ('personality', models.IntegerField(blank=True, null=True, verbose_name='性格')),
                ('identity', models.IntegerField(blank=True, null=True, verbose_name='個性')),
                ('item', models.IntegerField(blank=True, null=True, verbose_name='持ち物')),
                ('hp', models.IntegerField(blank=True, null=True, verbose_name='HP')),
                ('attack', models.IntegerField(blank=True, null=True, verbose_name='攻撃')),
                ('defence', models.IntegerField(blank=True, null=True, verbose_name='防御')),
                ('special_attack', models.IntegerField(blank=True, null=True, verbose_name='特殊攻撃')),
                ('special_defence', models.IntegerField(blank=True, null=True, verbose_name='特殊防御')),
                ('speed', models.IntegerField(blank=True, null=True, verbose_name='素早さ')),
                ('hp_effort', models.IntegerField(blank=True, null=True, verbose_name='HP努力値')),
                ('attack_effort', models.IntegerField(blank=True, null=True, verbose_name='攻撃努力値')),
                ('defence_effort', models.IntegerField(blank=True, null=True, verbose_name='防御努力値')),
                ('special_attack_effort', models.IntegerField(blank=True, null=True, verbose_name='特殊攻撃努力値')),
                ('special_defence_effort', models.IntegerField(blank=True, null=True, verbose_name='特殊防御努力値')),
                ('speed_effort', models.IntegerField(blank=True, null=True, verbose_name='素早さ努力値')),
                ('delete_flag', models.BooleanField(default=False, verbose_name='論理削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ポケモンの登録',
                'db_table': 'pokemon',
            },
        ),
    ]
