# Generated by Django 3.1.6 on 2022-06-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstpokemon',
            name='identity',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='個性'),
        ),
        migrations.AlterField(
            model_name='mstpokemon',
            name='item',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='持ち物'),
        ),
        migrations.AlterField(
            model_name='mstpokemon',
            name='personality',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='性格'),
        ),
    ]
