# Generated by Django 4.0.6 on 2022-10-10 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_api_app', '0002_delete_mstidentity_delete_mstitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstbattlerecord',
            name='party',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager_api_app.mstparty'),
            preserve_default=False,
        ),
    ]
