# Generated by Django 3.1.6 on 2022-06-24 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_api_app', '0003_auto_20220614_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstParty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('party_name', models.CharField(max_length=256, verbose_name='パーティ名')),
                ('delete_flag', models.BooleanField(default=False, verbose_name='論理削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('poke_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_api_app.mstpokemon', verbose_name='ポケモン名')),
            ],
            options={
                'verbose_name': 'パーティの登録',
                'db_table': 'party',
            },
        ),
    ]
