# Generated by Django 4.0.6 on 2022-10-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_api_app', '0004_alter_mstbattlerecord_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mstbattlerecord',
            name='party',
        ),
        migrations.AddField(
            model_name='mstbattlerecord',
            name='party_name',
            field=models.CharField(default='', max_length=256, verbose_name='パーティ名'),
            preserve_default=False,
        ),
    ]
