# Generated by Django 3.1.6 on 2022-06-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_api_app', '0004_mstidentity_mstitem_mstparty_mstpersonality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstparty',
            name='party_name',
            field=models.CharField(max_length=256, unique=True, verbose_name='パーティ名'),
        ),
    ]
