# Generated by Django 3.1.6 on 2022-06-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_api_app', '0006_auto_20220625_1435'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='MstIdentity',
        #     fields=[
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('category', models.CharField(max_length=20, verbose_name='個性の名前')),
        #         ('delete_flag', models.BooleanField(default=False, verbose_name='論理削除フラグ')),
        #         ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
        #         ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
        #     ],
        #     options={
        #         'verbose_name': '個性の登録',
        #         'db_table': 'identity',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='MstItem',
        #     fields=[
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('category', models.CharField(max_length=30, verbose_name='持ち物の名前')),
        #         ('description', models.CharField(max_length=255, verbose_name='持ち物の説明')),
        #         ('delete_flag', models.BooleanField(default=False, verbose_name='論理削除フラグ')),
        #         ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
        #         ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
        #     ],
        #     options={
        #         'verbose_name': '持ち物の登録',
        #         'db_table': 'item',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='MstPersonality',
        #     fields=[
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('category', models.CharField(max_length=20, verbose_name='性格の名前')),
        #         ('delete_flag', models.BooleanField(default=False, verbose_name='論理削除フラグ')),
        #         ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
        #         ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
        #     ],
        #     options={
        #         'verbose_name': '性格の登録',
        #         'db_table': 'personality',
        #     },
        # ),
        migrations.AlterField(
            model_name='mstparty',
            name='party_name',
            field=models.CharField(max_length=256, verbose_name='パーティ名'),
        ),
    ]
